version: '3'

services:
  station-service:
    image: nginx:stable
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8081:80"
    networks:
      - persium-dev-platform_persium
  station-php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/root/.ssh
    networks:
      - persium-dev-platform_persium
  station-psql:
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
        -   "54321:5432"
    environment:
      POSTGRES_PASSWORD: persium@123
    networks:
      - persium-dev-platform_persium
  station-redis:
    image: redis:alpine
    restart: always
    ports:
      - '6679:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxpersium@123!CDmwMtyKVge8oLd2t81
    volumes:
      - ./redis-data:/data
    networks:
      - persium-dev-platform_persium
networks:
  persium-dev-platform_persium:
    external: true


